version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      # usuario: postgres/password
      POSTGRES_PASSWORD: password
    volumes:
       - postgdb:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

# Names our volume
volumes:
  postgdb:
