version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      # usuario: postgres/password
      POSTGRES_PASSWORD: password
    volumes:
       - postgdb:/var/lib/postgresql/data
    ports:
       - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 80:80
  

# Names our volume
volumes:
  postgdb:
