version: '3.3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
#    command: redis-server --appendonly yes
    volumes:
      - data:/data


  commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

volumes:
  data:
